# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/go-sql-driver/mysql";
    fetch = {
      type = "git";
      url = "https://github.com/go-sql-driver/mysql";
      rev = "9181e3a86a19bacd63e68d43ae8b7b36320d8092";
      sha256 = "162sakir5969kgmqcnh6xa6f01gmhhlr2vgyad651chrn79m0phc";
    };
  }
  {
    goPackagePath = "github.com/lib/pq";
    fetch = {
      type = "git";
      url = "https://github.com/lib/pq";
      rev = "83612a56d3dd153a94a629cd64925371c9adad78";
      sha256 = "12334yigh284k5cdvb9pgxaq6n78205jcbp75ajz44vvfd4wi6qc";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-sqlite3";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-sqlite3";
      rev = "d5ffb5c0cca8778699a929b236766f4a7af674e8";
      sha256 = "1qpq4c1lhlnc1j09v5qar53j4p9yv10wy7sylpkl7d7mpyj4qcc8";
    };
  }
  {
    goPackagePath = "github.com/ziutek/mymysql";
    fetch = {
      type = "git";
      url = "https://github.com/ziutek/mymysql";
      rev = "1d19cbf98d83564cc561192ae7d7183d795f7ac7";
      sha256 = "11fhqx5kpzcygz68c6hk64rvhz8r6ch5dj1jvff97hygiqvmvv11";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "d866cfc389cec985d6fda2859936a575a55a3ab6";
      sha256 = "10iahqcsiih5hgmqw8yfgv5b3fimfwl1skxg5062avcjjks59f03";
    };
  }
]
