add_newline = false

[aws]
disabled = true

[gcloud]
disabled = true

# [docker]
# disabled = true

[terraform]
disabled = true


[time]
disabled = false
style = "white"
#format = "at $time($style) "
format = " [$time]($style) "

