add_newline = false

right_format = """
$directory"""

[aws]
disabled = true

[gcloud]
disabled = true

[docker_context]
disabled = true

[terraform]
disabled = true
format = "[$symbol$version]($style)"


[time]
disabled = false
style = "white"
#format = "at $time($style) "
format = " [$time]($style) "
